name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Build and Test on Linux
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install dependencies
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev libwxgtk3.0-dev wx3.0-headers

      - name: Install dependencies
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev libwxgtk3.2-dev wx3.2-headers          

      - name: Create build directory
        run: mkdir build && cd build && cmake ..

      - name: Build the project
        run: |
          cd build
          cmake --build . --parallel 4

      - name: Run tests
        run: |
          cd build
          ./png_metadata_reader ../test-image/placeholder.png
          ./png_metadata_reader ../test-image/placeholder.png Author="John Doe" Version="1.0"        
          ./png_metadata_reader ../test-image/placeholder.png

  build-windows:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install dependencies (vcpkg)
        run: |
          choco install cmake
          choco install wxwidgets
          choco install libpng

      - name: Create build directory
        run: |
            mkdir build
            cd build
            CMAKE_PREFIX_PATH=~/.conda/envs/ cmake ..

      - name: Build the project
        run: |
          cd build
          cmake --build .

      - name: Run tests
        run: |
          cd build
          .\png_metadata_reader.exe ../test-image/placeholder.png
          .\png_metadata_reader.exe ../test-image/placeholder.png Author="John Doe" Version="1.0"        
          .\png_metadata_reader.exe ../test-image/placeholder.png
